apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
  - name: app-container
    image: bgruening/busybox-bash
    #command: ['sh', '-c', 'for file in *; do if '[ ! -d '$file' ']; then echo $file cat $file; fi; done;sleep 3600']
    #command: ['/bin/bash', '-c', 'cd /etc/config; for file in *; do if [! -d "$file"]; then cat $file; fi; done']
    command: ['/bin/bash', '-c', 'cd /etc/config ; for file in *; do if [ ! -d "$file" ]; then printf "$file: $(cat "$file")\n"; fi; done']  
    volumeMounts:
      - name: configmapvolume
        mountPath: /etc/config
  volumes:
    - name: configmapvolume
      configMap:
        name: appconfig
