apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
  - name: app-container
    image: bgruening/busybox-bash
    command: ['/bin/bash', '-c', 'printf "## ConfigMap Files and Values ##\n"; cd /etc/config ; for file in *; do if [ ! -d "$file" ]; then printf "$file: $(cat "$file")\n"; fi; done']  
    volumeMounts:
      - name: configmapvolume
        mountPath: /etc/config
  volumes:
    - name: configmapvolume
      configMap:
        name: appconfig
